# Generated by Django 2.2 on 2022-09-12 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20220908_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, unique=True)),
                ('slug', models.CharField(max_length=500, unique=True)),
                ('posted_on', models.DateField(auto_now_add=True)),
                ('last_edit', models.DateField(auto_now_add=True, null=True)),
                ('content', models.CharField(max_length=10000)),
                ('hidden', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Category')),
                ('viewers', models.ManyToManyField(related_name='post_viewers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
